### PR TITLE
refactor: query mechanism to avoid Memory Leaks

### PR DESCRIPTION
**Pull request by anugrahsinghal**
## Summary of change
- QueryExecutorTemplate to do memory-safe queries.
- Added ArchUnit test to ensure the use of the QueryExecutorTemplate and avoid raw methods.
- Refactor all in-memory queries to make use of QueryExecutorTemplate

## Related issues
- #361

## Test Plan
Added ArchUnit dependency in the core package to ensure that any class in the queries package makes use of the QueryExecutorTemplate and does not call the raw methods.

## Documentation changes
NA

## Checklist for important updates
- [x] Changelog has been updated
    - [ ] If there are any db schema changes, mention those changes clearly
- [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
- [ ] `pluginInterfaceSupported.json` file has been updated (if needed)
- [ ] Changes to the version if needed
   - In `build.gradle`
- [x] Had installed and ran the pre-commit hook
- [ ] If there are new dependencies that have been added in `build.gradle`, please make sure to add them in `implementationDependencies.json`.
- [x] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
@anugrahsinghal the changes here make a lot of sense. This is a great way to solve the issue.

I will keep this PR open until similar changes have been made to MySQL + PostgreSQL repos.

**Comment by anugrahsinghal** [comment]
hey @rishabhpoddar 
added a few more commits, it's basically a refactoring to the name of a test case that I added

**Review by rishabhpoddar — APPROVED** [review]

**Comment by rishabhpoddar** [comment]
@anugrahsinghal i have updated these branch with the latest changes in the base branch. Can you please rerun the tests with a the sqlite (in mem) db and then I can merge this. Thanks.

**Comment by anugrahsinghal** [comment]
Screenshot 2022-02-17 at 3 43 08 PM

@rishabhpoddar All Tests passing with ImMemoryDB ☝️
core: branch refactor-query-mechnaism
env - gitpod

**Pull request merged**
