### PR TITLE
Add trap mechanism to handle term signals. Fixes #28

### LINKED ISSUE #28: (Intermediate) If running the docker image in foreground, sending a kill signal doesn't stop the container
To recreate the problem that exists today:
- run `docker pull supertokens/supertokens-mysql:2.4`
- Start the docker image in foreground: `docker run -p 3567:3567 supertokens/supertokens-mysql:2.4`
- Wait for it to start.. It should display `Started SuperTokens on 0.0.0.0:3567 with PID: <some PID>`
- Now send the kill signal (Ctrl + C / Z on a Mac)

At this point, the Java process in the docker process should stop and the docker process itself should quit. However, that does not happen.

The docker file for the above image can be found in [this repo](https://github.com/supertokens/supertokens-docker-mysql). Please feel free to fork that as well.

As some extra info:
- if not using docker (manually installing it on your system), sending the kill signal does stop the running process.
- In the Java code (this repo), in [Main.java](https://github.com/supertokens/supertokens-core/blob/master/src/main/java/io/supertokens/Main.java), there is [a function](https://github.com/supertokens/supertokens-core/blob/master/src/main/java/io/supertokens/Main.java#L354) that registers a shutdown hook.

### PR DESCRIPTION
**Pull request by Fabricio20**
This commit adds a trap mechanism around the exec call to pass the signals received by bash to a child process.

Due to added complexity and for better legibility, I've opted to move the source for both scripts from java to a resource.

These changes are based on [sigterm propagation](http://veithen.io/2014/11/16/sigterm-propagation.html).

I was not able to test the changes in their full extent, due to compilation issues on this project, I did however successfully test the change by overriding via volume mounts in docker. Let me know if this breaks windows compatibility or doesn't work after a full build.

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
@Fabricio20 thanks for the contribution. Will the `install-linux.sh` and `install-windows.bat` files get bundled in the JAR itself, or will these files also need to be distributed along with the JAR?

**Comment by Fabricio20** [comment]
Hey there, these two files come bundled in the final jar.

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya, could you please review this PR.

You need to build a docker image based on the forked core. Instructions on how to build a docker image can be found here: https://github.com/supertokens/supertokens-core/wiki/Building-from-source#creating-a-docker-image (here it says using mysql, but you can follow the same steps with sqlite as well)

Once the image is created, you need to test:
- Starting the docker image in background and querying it.. it should work.
- Starting the docker image in foregrdoun (with `-d`) and checking it works, then pressing ctrl + c and seeing that it quite smoothly.
- SSH into the docker image (which is not running using `docker run -it supertokens bash`). Then run `supertokens --help` and see the output is shown properly and that you gain control of the shell after the output is done.
- SSH into the docker image (which is not running using `docker run -it supertokens bash`). Then start supertokens using `supertokens start` and see that it starts in the background and that you can run `supertokens list` to see it.
- SSH into the docker image (which is not running using `docker run -it supertokens bash`). Then start it in the foreground using `supertokens start --foreground` and see it run. Then pressing ctrl + c should kill it.

Then independent to the docker image, install SuperTokens on your machine (using the forked core) using the instruction found here: https://github.com/supertokens/supertokens-core/wiki/Building-from-source#installing-manually

After installation:
- Run `supertokens start` to see it start in the background and then you can run `supertokens list` to see it and `supertokens stop` to stop it.
- Run `supertokens start --foreground` to see it run in the foreground, and then pressing ctrl + c should kill the process.
- Run `supertokens --help` to see the output of that and there should be nothing weird or something like `grep: /proc/1/cgroup: No such file or directory` being printed out in the console.

**Comment by bhumilsarvaiya** [comment]
Tested the following:
- [ ] Starting the docker image in background and querying it.. it should work.
- [ ] Starting the docker image in foreground (without -d) and checking it works, then pressing ctrl + c and seeing that it quite smoothly.
- [ ] SSH into the docker image (which is not running using docker run -it supertokens bash). Then run supertokens --help and see the output is shown properly and that you gain control of the shell after the output is done.
- [ ] SSH into the docker image (which is not running using docker run -it supertokens bash). Then start supertokens using supertokens start and see that it starts in the background and that you can run supertokens list to see it.
- [ ] SSH into the docker image (which is not running using docker run -it supertokens bash). Then start it in the foreground using supertokens start --foreground and see it run. Then pressing ctrl + c should kill it.
---
- [ ] Run supertokens start to see it start in the background and then you can run supertokens list to see it and supertokens stop to stop it.
- [ ] Run supertokens start --foreground to see it run in the foreground, and then pressing ctrl + c should kill the process.
- [ ] Run supertokens --help to see the output of that and there should be nothing weird or something like grep: /proc/1/cgroup: No such file or directory being printed out in the console.
---
Hey @Fabricio20, great work! All the docker tests are running correctly! ✌️ 
For the remaining of the supertokens test (i.e. when installed manually), I kept getting following message printed out whenever I tried to execute any cli command (the commands were getting executed correctly but this message was always getting printed):
```bash
grep: /proc/1/cgroup: No such file or directory
```
I was getting this issue on `macOS Catalina 10.15.7`.

I got it fixed by changing the `line 5` from file [`cli/src/main/resources/install-linux.sh`](https://github.com/Fabricio20/supertokens-core/blob/master/cli/src/main/resources/install-linux.sh):
```bash
if grep docker /proc/1/cgroup -qa; then
```
to
```bash
if [ -f /proc/1/cgroup ] && grep docker /proc/1/cgroup -qa; then
```
All the tests were passing after the above change.

---
For manually installed supertokens, if the process is started in foreground, the supertokens process seems to end but it doesn't seem to return back to terminal. I tried doing it couple of times but the issue remains. When I tried to exit the program using either `Ctrl + c` or `Ctrl + d`, this is what kept happening:
Screenshot 2020-10-07 at 6 57 54 PM

**Comment by rishabhpoddar** [comment]
@Fabrihcio20 , @bhumilsarvaiya , amazing work! Thank you.

@bhumilsarvaiya , the last problem you mentioned about running SuperTokens using `--foreground` is a [different issue](https://github.com/supertokens/supertokens-core/issues/49), and has nothing to do with this issue or the changes made for this issue.

**Comment by rishabhpoddar** [comment]
@Fabricio20 and @bhumilsarvaiya amazing work! Thank you.

The last problem you mentioned about running SuperTokens using --foreground is a different issue, and has nothing to do with this issue or the changes made for this issue.

**Pull request merged**
