### PR TITLE
Add Github Issues and PR Templates

### PR DESCRIPTION
**Pull request by NkxxkN**

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
- For question issue, will the question label be added automatically?
- Can we make `bug.md` a little less verbose? Having to add so many fields might annoy people.
- What is the point of `ISSUE_TEMPLATE.md`?
- Is there a way that I can just "escape" these templates to have a free writing experience (like what it is now)?

**Comment by NkxxkN** [comment]
Tested on a new repo I created https://github.com/NkxxkN/github-issue-template-testing/issues/new/choose

> Can we make bug.md a little less verbose? Having to add so many fields might annoy people.
Done

- No need for `ISSUE_TEMPLATE.md`. I removed it.

Is there a way that I can just "escape" these templates to have a free writing experience (like what it is now)?

Yes , open a blank issue.

image

**Comment by NkxxkN** [comment]
> For question issue, will the question label be added automatically?

For the question label, users will be encouraged to use discord. But if they decide to create the issue then the `question` label will be added.

or any other types of issues ,the label will be added automatically. 

image

**Comment by NkxxkN** [comment]
> From feature.md, can we remove the ## Pitch section? I feel the motivation section is good enough. We want as many feature requests as possible.
 > Can we remove the Have you read the.... #reporting-new-issues section as well? I don't get the purpose of it.

Done.

**Comment by rishabhpoddar** [comment]
In the questions issue, can we remove:
`Please note that this issue tracker is not a help form and this issue will be closed.`
It's a little confusing as to what that means. 

Also, am I supposed to:
- add the question in the title or body?
- remove the body completely or keep `## ❓ Questions and Help`?

The question label doesn't seem to get added automatically.

**Comment by rishabhpoddar** [comment]
One way to know if these template categories are good is to try and fit the existing issues into one of the templates. Please let me know if most (if not all) fit into these "naturally".

We want to keep the cognitive load to a minimum when creating a new issue. Generally, these are very useful to have once you are getting loads of external issues. Until then, we want to try and get as many as possible. 

But I do understand that having these makes it look more professional, so I'm happy to go ahead, provided that it doesn't add too much thinking from the issuer's side.

**Comment by NkxxkN** [comment]
> Also, am I supposed to:

As a user asking a question, you are supposed to keep the body with `## ❓ Questions and Help` but that's completely up to you if you prefer to remove it.

> One way to know if these template categories are good is to try and fit the existing issues into one of the templates

Looking at the issues we created so far ( and that is mostly you Rishabh) they all fall into either the "Bug" category or the "feature request" category). 

**Bug**:
  - Asking for details
  - Asking for stacktrace, screenshots, videos, etc..

**Feature Request**:
  - Feature Details
  - Implementation details (if relevant)

**Documentations** and **Questions** are just adding the tag to the issues, and adding a title.

I think in addition to make it more professional, this guides the users to raise their concerns/questions/issues and gives them confidence that they are doing it the right way. I personally always feel like it's easier to open a ticket when there are guidelines like this as I feel that I've provided all the necessary information for my ticket to be taken into account.

I reduced the sections to the minimum for now. Let's build upon this skeleton if we feel the need in the future.

**Comment by rishabhpoddar** [comment]
The `bug.md` files seems to be missing:
```
about: Submit a bug report to help us improve
labels: 'bug'
```

Apart from that, it all looks good. Please feel free to merge it whenever you are ready.

**Comment by NkxxkN** [comment]
> Please feel free to merge it whenever you are ready.

"Merging is blocked
The base branch restricts merging to authorized users."

You get the honor :)

**Comment by rishabhpoddar** [comment]
Ah! Done. Sorry about that. But I think from a liability point of view, it's best to have just one person be able to modify master.

**Pull request merged**
