### PR TITLE
2.5 api key rotation

### PR DESCRIPTION
**Pull request by NkxxkN**
Adding JWT API Key Rotation to `v2.5`

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
The code change looks fine. Two questions:
- Was there no plugin change required at all for SQL & for NoSQL?
- I feel like there were many tests involving JWT signing keys. `com-core` has about 350 tests, while `supertokens-core` has ~250 tests. Can you please see the differences and try to port in as many relevant tests as possible please?

**Comment by rishabhpoddar** [comment]
Oh! And please change the changelog date to today

**Comment by NkxxkN** [comment]
> Was there no plugin change required at all for SQL & for NoSQL?

No there was not. The code to get/set signing key was already there.

> I feel like there were many tests involving JWT signing keys. com-core has about 350 tests, while supertokens-core has ~250 tests. Can you please see the differences and try to port in as many relevant tests as possible please?

- [x] New commit created with updated tests.
- [x] For each diffs in the tests, explanation here https://github.com/NkxxkN/st-diffs/pull/2/files
- [x] Updated the changelog date.
- [x] Corrected CDI versions from bad copy/pasting :/

**Comment by rishabhpoddar** [comment]
There are totally still just 276 tests in the core. If you think that's all, please squash and merge this into bracnh `2.5` :)

**Pull request merged**
